### PR TITLE
Fix/service discovery

### LINKED ISSUE #95: Concurrent access to servers list leads to panic
Hi,

A concurrency bug can lead to server crashes in very specific circumstances when acessing and iterating over the map of servers by type returned.

The map returned by `GetServersByType`, from etcd's service discovery implementation is the same that is updated by the service discovery routine. This leads to possible concurrent read and write if the service discovery routine updates the map at the same time that another function is accessing the map, every request received by a front end server calls `GetServersByType`, so this is probably the most common user of the method.

Returning the map which is modified by the service can also lead to misuse of this structure and inconsistencies in the service discovery data.

### PR DESCRIPTION
**Pull request by andrehp**
Fixes #95

### CODE REVIEW

File: cluster/etcd_service_discovery.go [hunk 1]
```diff
@@ -74,13 +76,15 @@ func NewEtcdServiceDiscovery(
...
-		running:    false,
-		server:     server,
-		listeners:  make([]SDListener, 0),
-		stopChan:   make(chan bool),
-		appDieChan: appDieChan,
-		cli:        client,
+		config:          config,
+		running:         false,
+		server:          server,
+		serverMapByType: make(map[string]map[string]*Server, 0),
```
Comment (golangcibot) [inline cluster/etcd_service_discovery.go]: S1019: should use make(map[string]map[string]*Server) instead (from `gosimple`)

File: cluster/etcd_service_discovery.go [hunk 2]
```diff
@@ -230,10 +236,11 @@ func (sd *etcdServiceDiscovery) deleteServer(serverID string) {
 	if actual, ok := sd.serverMapByID.Load(serverID); ok {
 		sv := actual.(*Server)
 		sd.serverMapByID.Delete(sv.ID)
-		if svMap, ok := sd.serverMapByType.Load(sv.Type); ok {
-			sm := svMap.(map[string]*Server)
-			delete(sm, sv.ID)
+		sd.mapByTypeLock.Lock()
```
Comment (cscatolini) [inline cluster/etcd_service_discovery.go]: Isn't it better to `defer sd.mapByTypeLock.Unlock()` right after locking?

File: cluster/etcd_service_discovery.go [hunk 3]
```diff
@@ -267,10 +274,15 @@ func (sd *etcdServiceDiscovery) getServerFromEtcd(serverType, serverID string) (
 
 // GetServersByType returns a slice with all the servers of a certain type
 func (sd *etcdServiceDiscovery) GetServersByType(serverType string) (map[string]*Server, error) {
-	if m, ok := sd.serverMapByType.Load(serverType); ok {
-		sm := m.(map[string]*Server)
-		if len(sm) > 0 {
-			return sm, nil
+	sd.mapByTypeLock.RLock()
+	defer sd.mapByTypeLock.RUnlock()
+	if m, ok := sd.serverMapByType[serverType]; ok {
```
Comment (cscatolini) [inline cluster/etcd_service_discovery.go]: I don't like the nested if. Do you know if this works?

```
if m, ok := sd.serverMapByType[serverType]; ok && len(m) > 0 {
  ...
}
```

File: cluster/etcd_service_discovery.go [hunk 4]
```diff
@@ -267,10 +274,15 @@ func (sd *etcdServiceDiscovery) getServerFromEtcd(serverType, serverID string) (
...
+		if len(m) > 0 {
+			ret := make(map[string]*Server, len(sd.serverMapByType))
+			for k, v := range sd.serverMapByType[serverType] {
```
Comment (cscatolini) [inline cluster/etcd_service_discovery.go]: It is not obvious why your are iterating over a map to build the exact same map. I have the context by what we've talked and I had to think for a while before remembering it. I'd leave a comment here explaining why this is necessary.

File: cluster/etcd_service_discovery.go [hunk 5]
```diff
@@ -374,10 +384,11 @@ func parseServer(value []byte) (*Server, error) {
 }
 
 func (sd *etcdServiceDiscovery) printServers() {
-	sd.serverMapByType.Range(func(k, v interface{}) bool {
-		logger.Log.Debugf("type: %s, servers: %s", k, v)
-		return true
-	})
+	sd.mapByTypeLock.RLock()
```
Comment (cscatolini) [inline cluster/etcd_service_discovery.go]: Same here. Why not use `defer`?

File: cluster/etcd_service_discovery.go [hunk 6]
```diff
@@ -454,12 +466,14 @@ func (sd *etcdServiceDiscovery) revoke() error {
 
 func (sd *etcdServiceDiscovery) addServer(sv *Server) {
 	if _, loaded := sd.serverMapByID.LoadOrStore(sv.ID, sv); !loaded {
-		mapSvByType, ok := sd.serverMapByType.Load(sv.Type)
+		sd.mapByTypeLock.Lock()
```
Comment (cscatolini) [inline cluster/etcd_service_discovery.go]: Defer?

File: cluster/etcd_service_discovery.go (hunk 2 above)
Comment (andrehp) [reply cluster/etcd_service_discovery.go]: Given that there is only one flow deferring is slower and would be executed only after notifying the listeners

File: cluster/etcd_service_discovery.go (hunk 3 above)
Comment (andrehp) [reply cluster/etcd_service_discovery.go]: Yeah, I agree this looks better, I'm going to update it

File: cluster/etcd_service_discovery.go (hunk 4 above)
Comment (andrehp) [reply cluster/etcd_service_discovery.go]: Good idea

File: cluster/etcd_service_discovery.go (hunk 5 above)
Comment (andrehp) [reply cluster/etcd_service_discovery.go]: Defers are only useful when there multiple flows, in simple cases like this calling the function directly is a little more efficient

File: cluster/etcd_service_discovery.go (hunk 6 above)
Comment (andrehp) [reply cluster/etcd_service_discovery.go]: Same as above, using defer would keep the lock longer than needed

Comment (cscatolini) [reply cluster/etcd_service_discovery.go]: Same as my reply in the first comment about defers.

File: cluster/etcd_service_discovery.go (hunk 2 above)
Comment (andrehp) [reply cluster/etcd_service_discovery.go]: Ok, I created a wrapper for the lock, what do you think?

**Comment by cscatolini** [comment]
Great job 😍
